export const Defenders = {
  Smoke: "Smoke",
  Mute: "Mute",
  Castle: "Castle",
  Pulse: "Pulse",
  Doc: "Doc",
  Rook: "Rook",
  Kapkan: "Kapkan",
  Tachanka: "Tachanka",
  Jager: "Jager",
  Bandit: "Bandit",
  Frost: "Frost",
  Valkyrie: "Valkyire",
  Caviera: "Caveira",
  Echo: "Echo",
  Mira: "Mira",
  Lesion: "Lesion",
  Ela: "Ela",
  Vigil: "Vigil",
  Maestro: "Maestro",
  Alibi: "Alibi",
  Clash: "Clash",
  Kaid: "Kaid",
  Mozzie: "Mozzie",
  Warden: "Warden",
  Goyo: "Goyo",
  Wamai: "Wamai",
  Oryx: "Oryx",
  Melusi: "Melusi",
  Aruni: "Aruni",
  Thunderbird: "Thunderbird",
  Thorn: "Thorn",
  Azami: "Azami",
  Solis: "Solis",
  Fenrir: "Fenrir",
  Tubarao: "Tubarao",
  Sentry: "Sentry",
  Skopos: "Skopos",
} as const;

export const DefenderGadgets = {
  Smoke: "babe",
  Mute: "jammer",
  Castle: "armor_panel",
  Kapkan: "edd",
  Tachanka: "molly",
  Jager: "ads",
  Bandit: "batteries",
  Frost: "mats",
  Valkyire: "black_eye",
  Echo: "yokai",
  Mira: "window",
  Lesion: "gu",
  Ela: "grzmot",
  Maestro: "evil_eye",
  Alibi: "clone",
  Kaid: "claw",
  Mozzie: "pest",
  Goyo: "cans",
  Wamai: "disc",
  Oryx: "dash",
  Melusi: "banshee",
  Aruni: "surya",
  Fenrir: "fnat",
  Tubarao: "zoto",
} as const;

export const Attackers = {
  Sledge: "Sledge",
  Thatcher: "Thatcher",
  Ash: "Ash",
  Thermite: "Thermite",
  Twitch: "Twitch",
  Montagne: "Montagne",
  Glaz: "Glaz",
  Fuze: "Fuze",
  Blitz: "Blitz",
  IQ: "IQ",
  Buck: "Buck",
  Blackbeard: "Blackbeard",
  Capitao: "Capitao",
  Hibana: "Hibana",
  Jackal: "Jackal",
  Ying: "Ying",
  Zofia: "Zofia",
  Dokkaebi: "Dokkaebi",
  Lion: "Lion",
  Finka: "Finka",
  Maverick: "Maverick",
  Nomad: "Nomad",
  Gridlock: "Gridlock",
  Nokk: "Nokk",
  Amaru: "Amaru",
  Kali: "Kali",
  Iana: "Iana",
  Ace: "Ace",
  Zero: "Zero",
  Flores: "Flores",
  Osa: "Osa",
  Sens: "Sens",
  Grim: "Grim",
  Brava: "Brava",
  Ram: "Ram",
  Deimos: "Deimos",
  Striker: "Striker",
} as const;

export const AttackerGadgets = {
  Thatcher: "emp",
  Ash: "m120",
  Thermite: "brimstone",
  Twitch: "shock_drone",
  Fuze: "cluster_charge",
  Capitao: ["smoke_bolt", "fire_bolt"],
  Hibana: "xkarios",
  Ying: "candela",
  Zofia: ["impact_stun", "impact_concuss"],
  Dokkaebi: "call",
  Lion: "scan",
  Finka: "boost",
  Maverick: "torch",
  Nomad: "airjab",
  Gridlock: "trax",
  Amaru: "garra",
  Kali: "lance",
  Ace: "selma",
  Zero: "argus",
  Flores: "ratero",
  Osa: "clear_shield",
  Sens: "rou",
  Grim: "bees",
  Ram: "bugi",
  Deimos: "duel",
} as const;

const DefenderSecondaryGadgets = {
  C4: "C4",
  Shield: "Shield",
  BulletproofCamera: "BulletproofCamera",
  ObservationBlocker: "ObservationBlocker",
  BarbedWire: "BarbedWire",
  Impact: "Impact",
  ProximityAlarm: "ProximityAlarm",
} as const;

const AttackerSecondaryGadgets = {
  FragGrenade: "FragGrenade",
  Flashbang: "Flashbang",
  ImpactEmp: "ImpactEmp",
  CanOpener: "CanOpener",
  Claymore: "Claymore",
  Softbreach: "Softbreach",
} as const;

export const Operators = {
  ...Attackers,
  ...Defenders,
} as const;
